name: "Build Ren'Py-based Visual Novel"
author: 'SiegeWizard'
description: "Build your VN project using a specified Ren'Py SDK version"
inputs:
  sdk-version:
    description: "The version of the Ren'Py SDK to use"
    required: true
  project-dir:
    description: "The path to the directory where the project exists"
    required: false
    default: '.'
  package:
    description: "The package identifier to build for, defaults to all packages"
    required: false
    default: ""
outputs:
  dir:
    description: "The directory where the distributed files exist"
  version:
    description: "The built version of the project"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sdk-version }}
    - ${{ inputs.project-dir }}
    - ${{ inputs.package }}
branding:
  color: 'gray-dark'
  icon: 'book-open'
